### ISSUE TITLE
franka_control_node: malloc.c:2394: sysmalloc: Assertion REQUIRED process [franka_control-1] has died!

### ISSUE THREAD

**Issue by best-kk** [frankaemika/franka_ros#107]
I get this error when I launch franka_example_controller.launch.I used the newest franka_lib and franka_ros.

started roslaunch server http://superkai-OptiPlex-5040:41125/

SUMMARY
========

PARAMETERS
 * /cartesian_impedance_example_controller/arm_id: panda
 * /cartesian_impedance_example_controller/joint_names: ['panda_joint1', ...
 * /cartesian_impedance_example_controller/type: franka_example_co...
 * /cartesian_pose_example_controller/arm_id: panda
 * /cartesian_pose_example_controller/type: franka_example_co...
 * /cartesian_velocity_example_controller/arm_id: panda
 * /cartesian_velocity_example_controller/type: franka_example_co...
 * /dual_arm_cartesian_impedance_example_controller/left/arm_id: panda_2
 * /dual_arm_cartesian_impedance_example_controller/left/joint_names: ['panda_2_joint1'...
 * /dual_arm_cartesian_impedance_example_controller/right/arm_id: panda_1
 * /dual_arm_cartesian_impedance_example_controller/right/joint_names: ['panda_1_joint1'...
 * /dual_arm_cartesian_impedance_example_controller/type: franka_example_co...
 * /elbow_example_controller/arm_id: panda
 * /elbow_example_controller/type: franka_example_co...
 * /force_example_controller/arm_id: panda
 * /force_example_controller/joint_names: ['panda_joint1', ...
 * /force_example_controller/type: franka_example_co...
 * /franka_control/arm_id: panda
 * /franka_control/collision_config/lower_force_thresholds_acceleration: [20.0, 20.0, 20.0...
 * /franka_control/collision_config/lower_force_thresholds_nominal: [20.0, 20.0, 20.0...
 * /franka_control/collision_config/lower_torque_thresholds_acceleration: [20.0, 20.0, 18.0...
 * /franka_control/collision_config/lower_torque_thresholds_nominal: [20.0, 20.0, 18.0...
 * /franka_control/collision_config/upper_force_thresholds_acceleration: [20.0, 20.0, 20.0...
 * /franka_control/collision_config/upper_force_thresholds_nominal: [20.0, 20.0, 20.0...
 * /franka_control/collision_config/upper_torque_thresholds_acceleration: [20.0, 20.0, 18.0...
 * /franka_control/collision_config/upper_torque_thresholds_nominal: [20.0, 20.0, 18.0...
 * /franka_control/cutoff_frequency: 100
 * /franka_control/internal_controller: joint_impedance
 * /franka_control/joint_limit_warning_threshold: 0.1
 * /franka_control/joint_names: ['panda_joint1', ...
 * /franka_control/rate_limiting: True
 * /franka_control/realtime_config: enforce
 * /franka_control/robot_ip: 172.16.0.2
 * /franka_state_controller/arm_id: panda
 * /franka_state_controller/joint_names: ['panda_joint1', ...
 * /franka_state_controller/publish_rate: 30
 * /franka_state_controller/type: franka_control/Fr...
 * /joint_impedance_example_controller/acceleration_time: 2.0
 * /joint_impedance_example_controller/arm_id: panda
 * /joint_impedance_example_controller/coriolis_factor: 1.0
 * /joint_impedance_example_controller/d_gains: [50.0, 50.0, 50.0...
 * /joint_impedance_example_controller/joint_names: ['panda_joint1', ...
 * /joint_impedance_example_controller/k_gains: [600.0, 600.0, 60...
 * /joint_impedance_example_controller/publish_rate: 10.0
 * /joint_impedance_example_controller/radius: 0.1
 * /joint_impedance_example_controller/type: franka_example_co...
 * /joint_impedance_example_controller/vel_max: 0.15
 * /joint_position_example_controller/joint_names: ['panda_joint1', ...
 * /joint_position_example_controller/type: franka_example_co...
 * /joint_state_desired_publisher/rate: 30
 * /joint_state_desired_publisher/source_list: ['franka_state_co...
 * /joint_state_publisher/rate: 30
 * /joint_state_publisher/source_list: ['franka_state_co...
 * /joint_velocity_example_controller/joint_names: ['panda_joint1', ...
 * /joint_velocity_example_controller/type: franka_example_co...
 * /model_example_controller/arm_id: panda
 * /model_example_controller/type: franka_example_co...
 * /position_joint_trajectory_controller/constraints/goal_time: 0.5
 * /position_joint_trajectory_controller/constraints/panda_joint1/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint2/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint3/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint4/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint5/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint6/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint7/goal: 0.05
 * /position_joint_trajectory_controller/joints: ['panda_joint1', ...
 * /position_joint_trajectory_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    controller_spawner (controller_manager/spawner)
    franka_control (franka_control/franka_control_node)
    joint_state_desired_publisher (joint_state_publisher/joint_state_publisher)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    state_controller_spawner (controller_manager/spawner)

ROS_MASTER_URI=http://localhost:11311

process[franka_control-1]: started with pid [3626]
process[state_controller_spawner-2]: started with pid [3627]
process[robot_state_publisher-3]: started with pid [3628]
process[joint_state_publisher-4]: started with pid [3629]
process[joint_state_desired_publisher-5]: started with pid [3632]
process[controller_spawner-6]: started with pid [3633]
process[rviz-7]: started with pid [3634]
franka_control_node: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
INFO: cannot create a symlink to latest log directory: [Errno 2] No such file or directory: '/home/superkai/.ros/log/latest'
================================================================================REQUIRED process [franka_control-1] has died!
process has died [pid 3626, exit code -6, cmd /home/superkai/franka_ros/devel/lib/franka_control/franka_control_node __name:=franka_control __log:=/home/superkai/.ros/log/44cee110-bb3a-11ea-817f-14b31f0f89b4/franka_control-1.log].
log file: /home/superkai/.ros/log/44cee110-bb3a-11ea-817f-14b31f0f89b4/franka_control-1*.log
Initiating shutdown!
================================================================================
[INFO] [1593567226.467638]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1593567226.469255]: Controller Spawner: Waiting for service controller_manager/load_controller
[rviz-7] killing on exit
[controller_spawner-6] killing on exit
[joint_state_desired_publisher-5] killing on exit
[joint_state_publisher-4] killing on exit
[robot_state_publisher-3] killing on exit
[state_controller_spawner-2] killing on exit
[franka_control-1] killing on exit
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 39, in <module>
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 39, in <module>
        import joint_state_publisher
import joint_state_publisher
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/joint_state_publisher/__init__.py", line 38, in <module>
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/joint_state_publisher/__init__.py", line 38, in <module>
    import sensor_msgs.msg
    import sensor_msgs.msg
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/msg/__init__.py", line 9, in <module>
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/msg/__init__.py", line 9, in <module>
    from ._JointState import *
    from ._JointState import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/msg/_JointState.py", line 2, in <module>
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/sensor_msgs/msg/_JointState.py", line 2, in <module>
    """autogenerated by genpy from sensor_msgs/JointState.msg. Do not edit."""
    """autogenerated by genpy from sensor_msgs/JointState.msg. Do not edit."""
KeyboardInterrupt
KeyboardInterrupt
[WARN] [1593567226.700278]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1593567226.700966]: Controller Spawner couldn't find the expected controller_manager ROS interface.
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by gialen** [comment]
did you solved?
