### ISSUE TITLE
unknown error handler name 'rosmsg' when loading franka_state_controller

### ISSUE THREAD

**Issue by nbfigueroa** [frankaemika/franka_ros#113]
Hi!

We just received a new franka arm, we are using FCI version 4.0.1, libfranka version 0.8.0 and the kinetic-devel branch of franka_ros (we also tried the binary packages from the ROS repositories and had the same error), when launching franka_control as follows:

```python
roslaunch franka_control franka_control.launch robot_ip:=172.16.0.2
```
 we get the following error:

```python
SUMMARY
========

PARAMETERS
 * /franka_control/arm_id: panda
 * /franka_control/cutoff_frequency: 100
 * /franka_control/internal_controller: joint_impedance
 * /franka_control/joint_names: ['panda_joint1', ...
 * /franka_control/rate_limiting: True
 * /franka_control/robot_ip: 172.16.0.2
 * /franka_gripper/default_grasp_epsilon/inner: 0.005
 * /franka_gripper/default_grasp_epsilon/outer: 0.005
 * /franka_gripper/default_speed: 0.1
 * /franka_gripper/joint_names: ['panda_finger_jo...
 * /franka_gripper/publish_rate: 30
 * /franka_gripper/robot_ip: 172.16.0.2
 * /franka_state_controller/arm_id: panda
 * /franka_state_controller/joint_names: ['panda_joint1', ...
 * /franka_state_controller/publish_rate: 30
 * /franka_state_controller/type: franka_control/Fr...
 * /joint_state_desired_publisher/rate: 30
 * /joint_state_desired_publisher/source_list: ['franka_state_co...
 * /joint_state_publisher/rate: 30
 * /joint_state_publisher/source_list: ['franka_state_co...
 * /position_joint_trajectory_controller/constraints/goal_time: 0.5
 * /position_joint_trajectory_controller/constraints/panda_joint1/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint2/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint3/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint4/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint5/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint6/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint7/goal: 0.05
 * /position_joint_trajectory_controller/joints: ['panda_joint1', ...
 * /position_joint_trajectory_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    franka_control (franka_control/franka_control_node)
    franka_gripper (franka_gripper/franka_gripper_node)
    joint_state_desired_publisher (joint_state_publisher/joint_state_publisher)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    state_controller_spawner (controller_manager/spawner)

auto-starting new master
process[master]: started with pid [2255]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to cbff80ba-e7e3-11ea-88dc-848f69f797d1
process[rosout-1]: started with pid [2268]
started core service [/rosout]
process[franka_gripper-2]: started with pid [2285]
process[franka_control-3]: started with pid [2286]
[ INFO] [1598477616.722273582]: franka_gripper_node: Found default_speed 0.1
[ INFO] [1598477616.722944057]: franka_gripper_node: Found default_grasp_epsilon inner: 0.005, outer: 0.005
process[state_controller_spawner-4]: started with pid [2290]
process[robot_state_publisher-5]: started with pid [2312]
process[joint_state_publisher-6]: started with pid [2324]
process[joint_state_desired_publisher-7]: started with pid [2336]
[INFO] [1598477617.191945]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1598477617.193697]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1598477617.195059]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1598477617.196748]: Loading controller: franka_state_controller
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 207, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 185, in main
    resp = load_controller(name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: receive_once[/controller_manager/load_controller]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
[INFO] [1598477617.215429]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1598477617.215625]: Stopping all controllers...
[WARN] [1598477617.223038]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/controller_manager/switch_controller]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
```
Is there something we are missing?

**Comment by gollth** [comment]
Puhh, hard to say. ROS Kinetic [reached its retirement](http://wiki.ros.org/Distributions) in April 2021. In the near future franka_ros won't support Kinetic anymore either. Please try to use a newer ROS distribution such as Noetic and see if this helps. If not feel free to reopen this issue.
