### ISSUE TITLE
franka_control dies

### ISSUE THREAD

**Issue by GnnrMrkr** [frankaemika/franka_ros#70]
Hello everyone,

I try to control the Panda robot with ROS Melodic.  I tried a lot of things in simulation and now I try to work with the real robot. 

When trying to run specific parts of franka_ros, I always get errors that like 
`REQUIRED process [franka_control-1] has died!`

I tried to run all packages from [franka_ros]( https://frankaemika.github.io/docs/franka_ros.html) , but only the HW test (franka_hw franka_hw_test.test) and the visualization (franka_visualization franka_visualization.launch) works and looks fine. 

My OS is Ubuntu 18.04.2 LTS, running on a 
Intel® Xeon(R) CPU E3-1225 v3 @ 3.20GHz × 4. 

I already looked into other issues and these are the things that work or possible error sources I can exclude:

**Ping Test:**
```
[…]
--- 172.16.0.2 ping statistics ---
10000 packets transmitted, 10000 received, 0% packet loss, time 9998ms
rtt min/avg/max/mdev = 0.122/0.162/0.307/0.018 ms
```

**Echo Robot State works** (though not well formatted):
```
panda@boern-8:~$ cd libfranka/build/
panda@boern-8:~/libfranka/build$ ./examples/echo_robot_state
Usage: ./examples/echo_robot_state <robot-hostname>
panda@boern-8:~/libfranka/build$ ./examples/echo_robot_state 172.16.0.2
{"O_T_EE": [-0.964776,0.0863813,0.248487,0,0.243837,-0.0609248,0.967901,0,0.0987475,0.994398,0.0377158,0,0.0751279,0.0649383,1.13025,1], "O_T_EE_d": [1,0,0,0,0,-1,0,0,0,0,-1,0,0.088,0,0.926,1], "F_T_EE": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1], "EE_T_K": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1], "m_ee": 0.7, "F_x_Cee": [0,0,0], "I_ee": [0.001,0,0,0,0.001,0,0,0,0.001], "m_load": 0, "F_x_Cload": [0,0,0], "I_load": [0,0,0,0,0,0,0,0,0], "m_total": 0.7, "F_x_Ctotal": [0,0,0], "I_total": [0.001,0,0,0,0.001,0,0,0,0.001], "elbow": [-2.16897,1], "elbow_d": [0,1], "elbow_c": [0,0], "delbow_c": [0,0], "ddelbow_c": [0,0], "tau_J": [0.230636,2.91182,0.175241,-3.26469,0.0818798,0.762344,0.095393], "tau_J_d": [0,0,0,0,0,0,0], "dtau_J": [1.2411,51.2059,46.5436,-152.684,4.6843,-21.8679,-48.8285], "q": [1.85475,-0.0321982,-2.16897,-0.126436,1.7856,1.55162,-1.45504], "dq": [-0.000664768,-0.00086661,-0.000551295,0.000435586,-6.38721e-06,-0.000130034,0.000484985], "q_d": [0,0,0,0,0,0,0], "dq_d": [0,0,0,0,0,0,0], "ddq_d": [0,0,0,0,0,0,0], "joint_contact": [0,0,0,0,0,0,0], "cartesian_contact": [0,0,0,0,0,0], "joint_collision": [0,0,0,0,0,0,0], "cartesian_collision": [0,0,0,0,0,0], "tau_ext_hat_filtered": [0.213561,0.148066,0.0320331,0.00828305,-0.0541777,-0.541861,0.0663466], "O_F_ext_hat_K": [0,0,0,0,0,0], "K_F_ext_hat_K": [0,0,0,0,0,0], "O_dP_EE_d": [0,0,0,0,0,0], "O_T_EE_c": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], "O_dP_EE_c": [0,0,0,0,0,0], "O_ddP_EE_c": [0,0,0,0,0,0], "theta": [1.85477,-0.0319931,-2.16895,-0.126665,1.78561,1.55171,-1.45503], "dtheta": [0,0,0,0,0,0,0], "current_errors": [], "last_motion_errors": [], "control_command_success_rate": 0, "robot_mode": "Other", "time": 18351086}
```

My systems runs on a realtime Kernel: 
```
panda@boern-8:~$ uname -a
Linux boern-8 4.19.37-rt20-rc1 #1 SMP PREEMPT RT Wed Jun 5 15:10:01 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

`ros-melodic-ros-control` and `ros-melodic-controller-manager` are installed.

Here is one example of the outputs and errors I'm getting:
```
panda@boern-8:~$ roslaunch franka_example_controllers move_to_start.launch robot_ip:=172.16.0.2 load_gripper:=false
... logging to /home/panda/.ros/log/e0bced24-935e-11e9-bb2e-f4f26d060b53/roslaunch-boern-8-13578.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
 
WARNING: Package name "configV3" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://boern-8:37833/
 
SUMMARY
========
 
PARAMETERS
* /franka_control/arm_id: panda
* /franka_control/cutoff_frequency: 100
* /franka_control/internal_controller: joint_impedance
* /franka_control/joint_names: ['panda_joint1', ...
* /franka_control/rate_limiting: True
* /franka_control/robot_ip: 172.16.0.2
* /franka_state_controller/arm_id: panda
* /franka_state_controller/joint_names: ['panda_joint1', ...
* /franka_state_controller/publish_rate: 30
* /franka_state_controller/type: franka_control/Fr...
* /joint_state_desired_publisher/rate: 30
* /joint_state_desired_publisher/source_list: ['franka_state_co...
* /joint_state_publisher/rate: 30
* /joint_state_publisher/source_list: ['franka_state_co...
* /move_group/allow_trajectory_execution: True
* /move_group/controller_list: [{'default': True...
* /move_group/hand/planner_configs: ['SBLkConfigDefau...
* /move_group/jiggle_fraction: 0.05
* /move_group/max_range: 5.0
* /move_group/max_safe_path_cost: 1
* /move_group/moveit_controller_manager: moveit_simple_con...
* /move_group/moveit_manage_controllers: True
* /move_group/octomap_frame: camera_rgb_optica...
* /move_group/octomap_resolution: 0.05
* /move_group/panda_arm/planner_configs: ['SBLkConfigDefau...
* /move_group/panda_arm_hand/planner_configs: ['SBLkConfigDefau...
* /move_group/planner_configs/BFMTkConfigDefault/balanced: 0
* /move_group/planner_configs/BFMTkConfigDefault/cache_cc: 1
* /move_group/planner_configs/BFMTkConfigDefault/extended_fmt: 1
* /move_group/planner_configs/BFMTkConfigDefault/heuristics: 1
* /move_group/planner_configs/BFMTkConfigDefault/nearest_k: 1
* /move_group/planner_configs/BFMTkConfigDefault/num_samples: 1000
* /move_group/planner_configs/BFMTkConfigDefault/optimality: 1
* /move_group/planner_configs/BFMTkConfigDefault/radius_multiplier: 1.0
* /move_group/planner_configs/BFMTkConfigDefault/type: geometric::BFMT
* /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
* /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
* /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
* /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
* /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
* /move_group/planner_configs/BiESTkConfigDefault/range: 0.0
* /move_group/planner_configs/BiESTkConfigDefault/type: geometric::BiEST
* /move_group/planner_configs/BiTRRTkConfigDefault/cost_threshold: 1e300
* /move_group/planner_configs/BiTRRTkConfigDefault/frountier_node_ratio: 0.1
* /move_group/planner_configs/BiTRRTkConfigDefault/frountier_threshold: 0.0
* /move_group/planner_configs/BiTRRTkConfigDefault/init_temperature: 100
* /move_group/planner_configs/BiTRRTkConfigDefault/range: 0.0
* /move_group/planner_configs/BiTRRTkConfigDefault/temp_change_factor: 0.1
* /move_group/planner_configs/BiTRRTkConfigDefault/type: geometric::BiTRRT
* /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/ESTkConfigDefault/range: 0.0
* /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
* /move_group/planner_configs/FMTkConfigDefault/cache_cc: 1
* /move_group/planner_configs/FMTkConfigDefault/extended_fmt: 1
* /move_group/planner_configs/FMTkConfigDefault/heuristics: 0
* /move_group/planner_configs/FMTkConfigDefault/nearest_k: 1
* /move_group/planner_configs/FMTkConfigDefault/num_samples: 1000
* /move_group/planner_configs/FMTkConfigDefault/radius_multiplier: 1.1
* /move_group/planner_configs/FMTkConfigDefault/type: geometric::FMT
* /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
* /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
* /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
* /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
* /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
* /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
* /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
* /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
* /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
* /move_group/planner_configs/LBTRRTkConfigDefault/epsilon: 0.4
* /move_group/planner_configs/LBTRRTkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/LBTRRTkConfigDefault/range: 0.0
* /move_group/planner_configs/LBTRRTkConfigDefault/type: geometric::LBTRRT
* /move_group/planner_configs/LazyPRMkConfigDefault/range: 0.0
* /move_group/planner_configs/LazyPRMkConfigDefault/type: geometric::LazyPRM
* /move_group/planner_configs/LazyPRMstarkConfigDefault/type: geometric::LazyPR...
* /move_group/planner_configs/PDSTkConfigDefault/type: geometric::PDST
* /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
* /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
* /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
* /move_group/planner_configs/ProjESTkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/ProjESTkConfigDefault/range: 0.0
* /move_group/planner_configs/ProjESTkConfigDefault/type: geometric::ProjEST
* /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
* /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
* /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/RRTkConfigDefault/range: 0.0
* /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
* /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
* /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
* /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
* /move_group/planner_configs/SBLkConfigDefault/range: 0.0
* /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
* /move_group/planner_configs/SPARSkConfigDefault/dense_delta_fraction: 0.001
* /move_group/planner_configs/SPARSkConfigDefault/max_failures: 1000
* /move_group/planner_configs/SPARSkConfigDefault/sparse_delta_fraction: 0.25
* /move_group/planner_configs/SPARSkConfigDefault/stretch_factor: 3.0
* /move_group/planner_configs/SPARSkConfigDefault/type: geometric::SPARS
* /move_group/planner_configs/SPARStwokConfigDefault/dense_delta_fraction: 0.001
* /move_group/planner_configs/SPARStwokConfigDefault/max_failures: 5000
* /move_group/planner_configs/SPARStwokConfigDefault/sparse_delta_fraction: 0.25
* /move_group/planner_configs/SPARStwokConfigDefault/stretch_factor: 3.0
* /move_group/planner_configs/SPARStwokConfigDefault/type: geometric::SPARStwo
* /move_group/planner_configs/STRIDEkConfigDefault/degree: 16
* /move_group/planner_configs/STRIDEkConfigDefault/estimated_dimension: 0.0
* /move_group/planner_configs/STRIDEkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/STRIDEkConfigDefault/max_degree: 18
* /move_group/planner_configs/STRIDEkConfigDefault/max_pts_per_leaf: 6
* /move_group/planner_configs/STRIDEkConfigDefault/min_degree: 12
* /move_group/planner_configs/STRIDEkConfigDefault/min_valid_path_fraction: 0.2
* /move_group/planner_configs/STRIDEkConfigDefault/range: 0.0
* /move_group/planner_configs/STRIDEkConfigDefault/type: geometric::STRIDE
* /move_group/planner_configs/STRIDEkConfigDefault/use_projected_distance: 0
* /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
* /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
* /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
* /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
* /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
* /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
* /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
* /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
* /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
* /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
* /move_group/planner_configs/TrajOptDefault/type: geometric::TrajOpt
* /move_group/planning_plugin: ompl_interface/OM...
* /move_group/planning_scene_monitor/publish_geometry_updates: True
* /move_group/planning_scene_monitor/publish_planning_scene: True
* /move_group/planning_scene_monitor/publish_state_updates: True
* /move_group/planning_scene_monitor/publish_transforms_updates: True
* /move_group/request_adapters: default_planner_r...
* /move_group/sensors: [{'point_subsampl...
* /move_group/start_state_max_bounds_error: 0.1
* /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
* /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
* /move_group/trajectory_execution/allowed_start_tolerance: 0.01
* /position_joint_trajectory_controller/constraints/goal_time: 0.5
* /position_joint_trajectory_controller/constraints/panda_joint1/goal: 0.05
* /position_joint_trajectory_controller/constraints/panda_joint2/goal: 0.05
* /position_joint_trajectory_controller/constraints/panda_joint3/goal: 0.05
* /position_joint_trajectory_controller/constraints/panda_joint4/goal: 0.05
* /position_joint_trajectory_controller/constraints/panda_joint5/goal: 0.05
* /position_joint_trajectory_controller/constraints/panda_joint6/goal: 0.05
* /position_joint_trajectory_controller/constraints/panda_joint7/goal: 0.05
* /position_joint_trajectory_controller/joints: ['panda_joint1', ...
* /position_joint_trajectory_controller/type: position_controll...
* /robot_description: <?xml version="1....
* /robot_description_kinematics/panda_arm/kinematics_solver: kdl_kinematics_pl...
* /robot_description_kinematics/panda_arm/kinematics_solver_search_resolution: 0.005
* /robot_description_kinematics/panda_arm/kinematics_solver_timeout: 0.05
* /robot_description_planning/joint_limits/panda_finger_joint1/has_acceleration_limits: False
* /robot_description_planning/joint_limits/panda_finger_joint1/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_finger_joint1/max_acceleration: 0
* /robot_description_planning/joint_limits/panda_finger_joint1/max_velocity: 0.1
* /robot_description_planning/joint_limits/panda_finger_joint2/has_acceleration_limits: False
* /robot_description_planning/joint_limits/panda_finger_joint2/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_finger_joint2/max_acceleration: 0
* /robot_description_planning/joint_limits/panda_finger_joint2/max_velocity: 0.1
* /robot_description_planning/joint_limits/panda_joint1/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint1/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint1/max_acceleration: 3.75
* /robot_description_planning/joint_limits/panda_joint1/max_velocity: 2.175
* /robot_description_planning/joint_limits/panda_joint2/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint2/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint2/max_acceleration: 1.875
* /robot_description_planning/joint_limits/panda_joint2/max_velocity: 2.175
* /robot_description_planning/joint_limits/panda_joint3/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint3/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint3/max_acceleration: 2.5
* /robot_description_planning/joint_limits/panda_joint3/max_velocity: 2.175
* /robot_description_planning/joint_limits/panda_joint4/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint4/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint4/max_acceleration: 3.125
* /robot_description_planning/joint_limits/panda_joint4/max_velocity: 2.175
* /robot_description_planning/joint_limits/panda_joint5/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint5/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint5/max_acceleration: 3.75
* /robot_description_planning/joint_limits/panda_joint5/max_velocity: 2.61
* /robot_description_planning/joint_limits/panda_joint6/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint6/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint6/max_acceleration: 5
* /robot_description_planning/joint_limits/panda_joint6/max_velocity: 2.61
* /robot_description_planning/joint_limits/panda_joint7/has_acceleration_limits: True
* /robot_description_planning/joint_limits/panda_joint7/has_velocity_limits: True
* /robot_description_planning/joint_limits/panda_joint7/max_acceleration: 5
* /robot_description_planning/joint_limits/panda_joint7/max_velocity: 2.61
* /robot_description_semantic: <?xml version="1....
* /rosdistro: melodic
* /rosversion: 1.14.3
 
NODES
  /
    controller_spawner (controller_manager/spawner)
    franka_control (franka_control/franka_control_node)
    joint_state_desired_publisher (joint_state_publisher/joint_state_publisher)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    move_to_start (franka_example_controllers/move_to_start.py)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    state_controller_spawner (controller_manager/spawner)
 
ROS_MASTER_URI=http://localhost:11311
 
process[franka_control-1]: started with pid [13599]
WARNING: Package name "configV3" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
terminate called after throwing an instance of 'franka::CommandException'
  what():  libfranka: Set Collision Behavior command rejected: command not possible in the current mode!
process[state_controller_spawner-2]: started with pid [13607]
process[robot_state_publisher-3]: started with pid [13608]
process[joint_state_publisher-4]: started with pid [13609]
process[joint_state_desired_publisher-5]: started with pid [13610]
process[controller_spawner-6]: started with pid [13615]
process[move_group-7]: started with pid [13617]
process[move_to_start-8]: started with pid [13620]
[ INFO] [1561037159.778488516]: Loading robot model 'panda'...
```
Then comes the crucial section:
```
================================================================================
REQUIRED process [franka_control-1] has died!
process has died [pid 13599, exit code -6, cmd /home/panda/catkin_ws/devel/lib/franka_control/franka_control_node __name:=franka_control __log:=/home/panda/.ros/log/e0bced24-935e-11e9-bb2e-f4f26d060b53/franka_control-1.log].
log file: /home/panda/.ros/log/e0bced24-935e-11e9-bb2e-f4f26d060b53/franka_control-1*.log
Initiating shutdown!
================================================================================
```

```
[move_to_start-8] killing on exit
[move_group-7] killing on exit
[controller_spawner-6] killing on exit
Traceback (most recent call last):
  File "/home/panda/catkin_ws/src/franka_ros/franka_example_controllers/scripts/move_to_start.py", line 3, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 26, in <module>
    from ._UInt16MultiArray import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_UInt16MultiArray.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/UInt16MultiArray.msg. Do not edit."""
KeyboardInterrupt
[joint_state_desired_publisher-5] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/joint_state_publisher/joint_state_publisher", line 3, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 8, in <module>
    from ._Float32 import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_Float32.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/Float32.msg. Do not edit."""
KeyboardInterrupt
[joint_state_publisher-4] killing on exit
[robot_state_publisher-3] killing on exit
[state_controller_spawner-2] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 36, in <module>
    import rosparam
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosparam/__init__.py", line 65, in <module>
    import rosgraph
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/__init__.py", line 36, in <module>
    from . masterapi import Master, MasterFailure, MasterError, MasterException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 41, in <module>
    from xmlrpc.client import ServerProxy  # Python 3.x
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 68, in <module>
    import rosgraph.network
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 48, in <module>
    import platform
  File "/usr/lib/python2.7/platform.py", line 1393, in <module>
    r'([\w.+]+)\s*'
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 558, in _code
    _compile_info(code, p, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 437, in _compile_info
    lo, hi = pattern.getwidth()
  File "/usr/lib/python2.7/sre_parse.py", line 177, in getwidth
    elif op in REPEATCODES:
KeyboardInterrupt
[franka_control-1] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/joint_state_publisher/joint_state_publisher", line 3, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 49, in <module>
    import rosgraph
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/__init__.py", line 36, in <module>
    from . masterapi import Master, MasterFailure, MasterError, MasterException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 41, in <module>
    from xmlrpc.client import ServerProxy  # Python 3.x
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 60, in <module>
    from SimpleXMLRPCServer import SimpleXMLRPCServer #Python 2.x
  File "/usr/lib/python2.7/SimpleXMLRPCServer.py", line 102, in <module>
    import xmlrpclib
  File "/usr/lib/python2.7/xmlrpclib.py", line 145, in <module>
    import httplib
  File "/usr/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/lib/python2.7/io.py", line 51, in <module>
    import _io
KeyboardInterrupt
Starting planning scene monitors...
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 36, in <module>
    import rosparam
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosparam/__init__.py", line 63, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 8, in <module>
    from loader import *
  File "/usr/lib/python2.7/dist-packages/yaml/loader.py", line 4, in <module>
    from reader import *
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 47, in <module>
    class Reader(object):
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 140, in Reader
    NON_PRINTABLE = re.compile(u'[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD\U00010000-\U0010ffff]')
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 561, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 107, in _compile
    _compile_charset(av, flags, code, fixup, fixes)
  File "/usr/lib/python2.7/sre_compile.py", line 232, in _compile_charset
    flags & SRE_FLAG_UNICODE):
  File "/usr/lib/python2.7/sre_compile.py", line 274, in _optimize_charset
    r = range(av[0], av[1]+1)
KeyboardInterrupt
Planning scene monitors started.
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
 
You can start planning now!
 
shutting down processing monitor...
... shutting down processing monitor complete
done

```

Depending on the package I run, I see a window (probably RViz) popping up and disappearing in the same second, while that output is created.

The configV3 should not be related to my problem. It is a package related to the MoveIt Setup Assistant Wizard. I replaced it with another name but had difficulties removing it completely. 

I saw this idea, but I don't find "features" under settings. Maybe I'm in the wrong settings? What exactly is meant with "Desk"?
> Please open Desk and check `Settings -> System -> Features`. Do you see there the `FCI (Franka Control Interface)` feature? This will be removed after a factory reset. If you don't have this feature file, please contact `support@franka.de` or your local supplier. (Similar to issue [38](https://github.com/frankaemika/libfranka/issues/38))

_Originally posted by @sgabl in https://github.com/frankaemika/franka_ros/issues/57#issuecomment-476168902_

I hope, you can help me!

Thank you very much!

**Comment by sgabl** [comment]
Hi,

thanks for the detailed description!
As you get the robot state, the FCI feature is installed. You can access the Desk programming environment in your setup by navigating to `https://172.16.0.2/`

Having a look at the `robot_mode` (output of `./examples/echo_robot_state 172.16.0.2`) and `what():  libfranka: Set Collision Behavior command rejected: command not possible in the current mode!` I assume that the `fail-safe safety locking system` is not opened or the `external activation device` is not toggled / opened. You can open the `fail-safe safety locking system` in the Desk environment.

**Comment by GnnrMrkr** [comment]
Thanks a lot! 

This resolved my issue.
